//q20 

let guestlist = ["shadab", "rashid", "omar", "hashir"]

let finalguestlist = guestlist.length

let list = (`i m inviting'${finalguestlist}'guests on the dinner tonight`);
 console.log(list);

//q21

fav_things = []
    fav_things.push("makkah");
    fav_things.push("madina");
    fav_things.push("tauseef");
    fav_things.push("naqab");
    fav_things.push("islam");
    fav_things.push("huzoor pbuh");
    fav_things.push("ibadat");
    fav_things.push("mere bacche");

console.log(fav_things);